version: '3.9'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'